// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfbssmplzvfubdidprom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmYnNzbXBsenZmdWJkaWRwcm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMzI4MTAsImV4cCI6MjA3ODYwODgxMH0.abI9fBl_dnHTKhHLPxh1kpDBU1ES_JT_dhv-502hHZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});